#monolog:
#  handlers:
#    # this "file_log" key could be anything
#    file_log:
#      type: stream
#      path: "%kernel.logs_dir%/%kernel.environment%.log"
#      # log *all* messages (debug is lowest level)
#      level: error