parameters:
    redis_host:     '127.0.0.1'
    redis_port:     6379
    redis_db:       1
    redis_dsn:      'redis://%redis_host%:%redis_port%/%redis_db%'

    redis_session_host:    '%redis_host%'
    redis_session_port:    '%redis_port%'
    redis_session_db:      1

services:
    redis_session.client:
        class: Redis
        calls:
            - connect:
                  $host: '%redis_session_host%'
                  $port: '%redis_session_port%'
            - select:
                  - '%redis_session_db%'
